### ISSUE TITLE
"Open Mods Folder" and "Close" buttons are swapped

### ISSUE THREAD

**Issue by ffogells** [mooziii/tpshud-fabric#10]
If i dont have YACL installed you get the screen with 4 buttons but "open mod folder" and "close" are switched with eachother

**Comment by mooziii** [comment]
Which version are you using? This should have been fixed in 1.6.4+1.19.4

**Comment by ffogells** [comment]
> 

1.19.3

**Comment by mooziii** [comment]
Yeah you should consider updating to the 1.19.4 version. If you really need to use 1.19.3 you can just stay with this version (as the bug isn't breaking anything really) or try to use the 1.19.4 version in 1.19.3 but I don't really recommend that
