### ISSUE TITLE
Crash when Launching

### ISSUE THREAD

**Issue by Clownarchy** [mooziii/tpshud-fabric#13]
I don't really understand what the reason for the crash is, but logs point to TPS HUD. Maybe a mod incompatibility? Game starts & runs fine with TPS HUD disabled.

I'm on Fabric 1.21.

> ---- Minecraft Crash Report ----
> // Hi. I'm Minecraft, and I'm a crashaholic.
> 
> Time: 2024-07-05 20:07:08
> Description: Initializing game
> 
> java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'tpshud'!
> 	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:388)
> 	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
> 	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:386)
> 	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
> 	at net.minecraft.class_310.<init>(class_310.java:477)
> 	at net.minecraft.client.main.Main.main(Main.java:239)
> 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
> 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
> 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
> 	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100)
> 	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
> 	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
> Caused by: java.lang.ExceptionInInitializerError
> 	at me.obsilabor.tpshud.networking.NetworkingListener.<clinit>(NetworkingListener.kt:14)
> 	at me.obsilabor.tpshud.TpsHud.onInitializeClient(TpsHud.kt:19)
> 	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384)
> 	... 9 more
> Caused by: net.minecraft.class_151: Non [a-z0-9/._-] character in path of location: minecraft:tpshud:handshake
> 	at net.minecraft.class_2960.method_45137(class_2960.java:285)
> 	at net.minecraft.class_2960.method_60656(class_2960.java:60)
> 	at net.minecraft.class_8710.method_56483(class_8710.java:27)
> 	at me.obsilabor.tpshud.networking.CommonHandshakePayload.<clinit>(CommonHandshakePayload.kt:9)
> 	... 12 more

[crash-2024-07-05_20.07.08-client.txt](https://github.com/user-attachments/files/16114678/crash-2024-07-05_20.07.08-client.txt)

**Comment by Blocks789** [comment]
same here

**Comment by mooziii** [comment]
Hey, I fixed the issues as soon as I could. Thank you for reporting. Fixed version:
https://modrinth.com/plugin/tps-hud/version/1.7.3+1.21
