### ISSUE TITLE
[Question] how does this work mod ?

### ISSUE THREAD

**Issue by iTrooz** [mooziii/tpshud-fabric#14]
If I understand the code correctly, this mod supports both
- an implementation using packet receive time for when the server doesn't have the mod installed
- a custom packet that can be sent by the server if it has the mod installed

And that the mod will automatically use the custom packet rather than the packet timing impl, if possible.

Could you please confirm this ? I'd like to use this mod on my server, but I'd like accurate TPS, so to ensure that I'm not using the timing-based method

Also, I think it would be great if you clarified that on your README/Modrinth page. "Optional server side mod" raised more questions for me than it answered

**Comment by mooziii** [comment]
Yes that is correct. The mod will automatically prefer the custom packet over the packet timing method. You'll be notified through a toast message if the custom packet is in use. You can also disable this toast in the config if you think it is annoying.
I will clarify that on my Modrinth page soon. 

Sorry for the late answer :/

**Comment by iTrooz** [comment]
No problem ! Thank you for your work
