### ISSUE TITLE
Why truncate TPS?

### ISSUE THREAD

**Issue by Moutard3** [mooziii/tpshud-fabric#15]
Why not display the exact TPS as a float?

If there's a technical limitation, why not round it? Truncating seems odd.

**Comment by mooziii** [comment]
Hi, this will be changed in a future update.

**Comment by Shiginima** [comment]
looking forward to that in v1.20.1

**Comment by mcgamerguy** [comment]
has this been added? i saw the "Satisfy TPS count" setting and turned it off, but im still only getting full TPS numbers, no floats

**Comment by mooziii** [comment]
New version is out: https://modrinth.com/plugin/tps-hud/version/1.7.4+1.21.4
