### ISSUE TITLE
Even more config 

### ISSUE THREAD

**Issue by Julienraptor01** [mooziii/tpshud-fabric#4]
Could it be possible to disable shadow on the text so that i can make it sodium-extra styled ?
![2022-07-05_17 01 58](https://user-images.githubusercontent.com/49841713/177358717-e9c7287e-a665-4aa1-be19-7fc22dc1b79b.png)

**Comment by mooziii** [comment]
Currently not possible but i will add this very soon

**Comment by mooziii** [comment]
New version **1.4.2+1.19** now allows you to remove the text shadow via the config screen
![image](https://user-images.githubusercontent.com/63669478/177400767-d59815ac-16da-4603-aa3f-7bc607c8a12e.png)

Download it from Modrinth: https://modrinth.com/mod/2UeET9aA/version/dzaKCTDt
Curseforge usually takes 2-12 hours to approve the file
