### ISSUE TITLE
Not sure how to config to get rid of white background

### ISSUE THREAD

**Issue by Scuzmb** [mooziii/tpshud-fabric#7]
More of an issue on my part but I do need help

**Comment by mooziii** [comment]
1. Install [modmenu](https://modrinth.com/mod/modmenu) and [yacl](https://modrinth.com/mod/yacl)
2. Open the config screen of tpshud via ModMenu
3. Disable the "Background" option

**Comment by Scuzmb** [comment]
Already had those, but no config button for tpshud in the mod menu

**Comment by mooziii** [comment]
Hi! Sorry for me not checking on this first but I now released an update which should fix the issue. (worked for me at least..) If you still encounter the problem after updating, please try updating ModMenu and YACL to the newest version too

**Comment by mooziii** [comment]
works for me so I assume its fine?
